spring:
  datasource:
    url: jdbc:mysql://localhost/pelayo
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
      org.springframework.security: debug